package com.example.IiitbHandshakeBackend;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.junit.runner.RunWith;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.io.IOException;

@SpringBootTest
public class LoginTestValid {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1() throws InterruptedException, IOException{
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1154, 694));
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("pragya");
    driver.findElement(By.id("examplePassword")).click();
    driver.findElement(By.id("examplePassword")).sendKeys("123");
    {
      WebElement dropdown = driver.findElement(By.id("select"));
      dropdown.findElement(By.xpath("//option[. = 'Student']")).click();
    }
    {
      WebElement element = driver.findElement(By.id("select"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("select"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("select"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".form-check")).click();
    Thread.sleep(2500);
    driver.findElement(By.cssSelector(".form-check-input")).click();
    Thread.sleep(2500);
    driver.findElement(By.cssSelector(".btn-secondary")).click();
    Thread.sleep(2500);
    driver.findElement(By.linkText("Logout")).click();
    Thread.sleep(2500);
  }
}